version: "3"
services:
  #rabbitmq:
  #  image: rabbitmq:3
  #  environment:
  #  - RABBITMQ_DEFAULT_USER=guest
  #  - RABBITMQ_DEFAULT_PASS=guest
  #  ports:
  #    - "127.0.0.1:5672:5672"

  #c:
  #  build:
  #    context: .
  #    dockerfile: c.Dockerfile

  #cs:
  #  build:
  #    context: .
  #    dockerfile: cs.Dockerfile

  #erlang:
  #  build:
  #    context: .
  #    dockerfile: erlang.Dockerfile

  #go:
  #  build:
  #    context: .
  #    dockerfile: go.Dockerfile

  #haskell:
  #  build:
  #    context: .
  #    dockerfile: haskell.Dockerfile

  #java:
  #  build:
  #    context: .
  #    dockerfile: java.Dockerfile

  #js:
  #  build:
  #    context: .
  #    dockerfile: js.Dockerfile

  #ocaml:
  #  build:
  #    context: .
  #    dockerfile: ocaml.Dockerfile

  #php:
  #  build:
  #    context: .
  #    dockerfile: php.Dockerfile

  python:
   build:
     context: .
     dockerfile: python.Dockerfile

  #ruby:
  #  build:
  #    context: .
  #    dockerfile: ruby.Dockerfile

  #rust:
  #  build:
  #    context: .
  #    dockerfile: rust.Dockerfile

  #scala:
  #  build:
  #    context: .
  #    dockerfile: scala.Dockerfile

